<a href="https://colab.research.google.com/github/s0ku00/DTS/blob/main/Grade_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [44]:
# 1-D array
grades = np.array( [85, 90, 88, 92, 95, 80, 75, 98, 89, 83] )
print(grades)

[85 90 88 92 95 80 75 98 89 83]


In [26]:
print("Mean:", np.mean(grades))

Mean: 87.5


In [27]:
print("Median:", np.median(grades))

Median: 88.5


In [28]:
print("Standard deviation:", np.std(grades))

Standard deviation: 6.591661399070799


In [11]:
# Maximum and Minimum Values
print("The maximum grade is", np.max(grades))
print("The minimun grade is", np.min(grades))

The maximum grade is 98
The minimun grade is 75


In [46]:
# Grades in ascending order
print(np.sort(grades))

[75 80 83 85 88 89 90 92 95 98]


In [43]:
# Index of the highest grade
print(np.argmax(grades))

7


In [24]:
# Number of students who scored above 90
print(np.count_nonzero(grades > 90))

3


In [40]:
# Percentage of students who scored above 90
print(f"{np.mean(grades > 90) * 100}%")

30.0%


In [39]:
# Percentage of students who scored below 75
print(f"{np.mean(grades < 75)}%")

0.0%


In [36]:
# Grades above 90
high_performers = np.array(grades[grades > 90])
print(high_performers)

[92 95 98]


In [45]:
# Grades above 75
passing_grades = np.array(grades[grades > 75])
print(passing_grades)

[85 90 88 92 95 80 98 89 83]
